
steps:
  - name: hashicorp/terraform:1.5
    entrypoint: sh
    args:
      - -c
      - |
        cd terraform
        terraform init
        terraform apply -auto-approve \
          -var="project_id=$PROJECT_ID" \
          -var="github_owner=your-github-username" \
          -var="github_repo=your-repo-name"

  # Terraform plan
  - name: 'hashicorp/terraform:1.5'
    dir: 'terraform'
    args: ['plan', '-input=false', '-out=tfplan']

  # Terraform apply
  - name: 'hashicorp/terraform:1.5'
    dir: 'terraform'
    args: ['apply', '-input=false', '-auto-approve', 'tfplan']

timeout: 600s
options:
  logging: CLOUD_LOGGING_ONLY
  #1
